### ISSUE TITLE
Migration from manifest version 2 to manifest version 3

### ISSUE THREAD

**Issue by gkm0001** [OpenLake/WatchParty#19]
mv2 is old version and The Chrome Web Store no longer accepts Manifest V2 extensions. That why it is not working.

<img width="928" alt="Screenshot 2023-12-18 205721" src="https://github.com/OpenLake/WatchParty/assets/121250607/d57ade43-a4fe-47e2-af26-4dd761c7040c">

**Comment by gkm0001** [comment]
I want to work on this assign it to me.

**Comment by chaitanyabisht** [comment]
Migration to V3 is the main goal. This area needs some work as there have been significant changes in how service workers run in the background. Feel free to propose any ideas you may have to migrate to V3 while maintaining the original functionality.

**Comment by Snehil-Shah** [comment]
@chaitanyabisht I am trying to set up the extension to work on my machine, it's not working.. is this the problem? or am I setting it up wrong?

**Comment by chaitanyabisht** [comment]
> @chaitanyabisht I am trying to set up the extension to work on my machine, it's not working.. is this the problem? or am I setting it up wrong?

The manifest V2 extension was working fine last year. Could you elaborate on the issue? Are you running the server as well?

**Comment by Snehil-Shah** [comment]
Yes the server is running

![image](https://github.com/OpenLake/WatchParty/assets/130062020/6dcd8c6e-fc1c-4a72-96d3-e602b114ef32)
First up I see this error when starting the extension.
And you don't see the Socket Status on the extensions as well (not connected to server etc)

I disabled the integrity check and added some logs to debug
![image](https://github.com/OpenLake/WatchParty/assets/130062020/250c15f8-0941-4639-9807-e81ee2e2b4ab)
The form definitely works and buttons are working, but nothing happens after form submission

the button onclick listener is sending a chrome runtime message, so added logs onto this runtime message listeners
![image](https://github.com/OpenLake/WatchParty/assets/130062020/9def4ccd-5b78-4b5e-9cce-74b0d6fa31c3)
![image](https://github.com/OpenLake/WatchParty/assets/130062020/d5c545c6-8d27-49d7-b522-c0f4af0cfe85)
and turns out the code never enters these blocks.
I added a bunch of other logpoints in functions like checkStatus which is being called, and socketStatus runtime message event listener that is responsible for the server status button , but No it never enters these blocks

can you check if its working for you? there's a chance I might have messed something up in the setup

**Comment by gkm0001** [comment]
How can  I solve that problem when migration from mv2 to mv3 

<img width="699" alt="Screenshot 2023-12-19 173811" src="https://github.com/OpenLake/WatchParty/assets/121250607/4141c73e-f352-4fd3-98a0-e35866252c9b">

<img width="517" alt="Screenshot 2023-12-19 173826" src="https://github.com/OpenLake/WatchParty/assets/121250607/abbdcf32-5bd4-44ce-b0a8-fd7dfc72e8fe">

I don't know how to solve this problem . I tried many times.

**Comment by gkm0001** [comment]
@chaitanyabisht  please look into it.

**Comment by Snehil-Shah** [comment]
@gkm0001 are you able to get version 2 running or you are facing the same problem as me?

**Comment by gkm0001** [comment]
NO , I am not able to running version 2

**Comment by chaitanyabisht** [comment]
I tested the extension and server with a fresh pull, and it is working. I can connect to the server, join rooms and chat. Although the seeking functionality isn't working right now, probably because of some change on YouTube's end.

@Snehil-Shah Check if the server is running, and check if your firewall or any other configuration is blocking access to the port 4000.

@gkm0001 Keep the manifest version 2 when testing, since it's still supported by Chrome right now, and will be deprecated soon.

**Comment by gkm0001** [comment]
OK
